services: 
  node-app: 
    build :
      context : .
      target : development
    # build:
    #   context: .
    #   args:
    #     - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    networks:
      - app-network
# command: ["npm", "run", "start-dev"]